common:
  orchestrator_common:
    attributes:
      deployment_mode: multinode_compute
    task_uuid: deployment_task

  openstack_common:
   internal_virtual_ip: 10.49.63.127
   public_virtual_ip: 10.49.54.127
   create_networks: true
   fixed_range: 192.168.0.0/16
   floating_range: 10.49.54.0/24
   swift_loopback: loopback
   nv_physical_volumes:
    - /dev/sdz
    - /dev/sdy
   external_ip_info:
     public_net_router: 10.49.54.1
     ext_bridge: 10.49.54.15
     pool_start: 10.49.54.225
     pool_end: 10.49.54.239
   segment_range: 900:999
   tenant_network_type: gre
   network_manager: nova.network.manager.FlatDHCPManager
   auto_assign_floating_ip: true
   quantum_netnode_on_cnt: true
   use_syslog: true
   syslog_server: 10.49.63.12
   mirror_type: default
   quantum: true
   internal_interface: eth0
   public_interface: eth1
   private_interface: eth2
   public_netmask: 255.255.255.0
   internal_netmask: 255.255.255.0
   default_gateway: 10.0.1.100
   nagios_master: fuel-controller-01.localdomain
   cinder: true
   cinder_nodes:
   - controller
   swift: true
   repo_proxy: http://10.0.0.100:3128
   deployment_id: '53'
   dns_nameservers:
   - 10.0.0.100
   - 8.8.8.8
   nodes:
   - name: fuel-cobbler
     role: cobbler
     internal_address: 10.0.0.100
     public_address: 10.0.1.100
   - name: fuel-controller-01
     role: primary-controller
     internal_address: 10.0.0.101
     public_address: 10.0.1.101
     swift_zone: 1
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.101
   - name: fuel-controller-02
     role: controller
     internal_address: 10.0.0.102
     public_address: 10.0.1.102
     swift_zone: 2
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.102
   - name: fuel-controller-03
     role: controller
     internal_address: 10.0.0.104
     public_address: 10.0.1.104
     swift_zone: 3
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.104
   - name: fuel-compute-01
     role: compute
     internal_address: 10.0.0.105
     public_address: 10.0.1.105
   - name: fuel-compute-02
     role: compute
     internal_address: 10.0.0.106
     public_address: 10.0.1.106
   - name: fuel-compute-03
     role: compute
     internal_address: 10.0.0.107
     public_address: 10.0.1.107
   - name: fuel-swift-01
     role: storage
     internal_address: 10.0.0.108
     public_address: 10.0.1.108
     swift_zone: 4
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.108
   - name: fuel-swift-02
     role: storage
     internal_address: 10.0.0.109
     public_address: 10.0.1.109
     swift_zone: 5
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.109
   - name: fuel-swift-03
     role: storage
     internal_address: 10.0.0.110
     public_address: 10.0.1.110
     swift_zone: 6
     mountpoints: 1 2\n 2 1
     storage_local_net_ip: 10.0.0.110
   - name: fuel-swiftproxy-01
     role: primary-swift-proxy
     internal_address: 10.0.0.111
     public_address: 10.0.1.111
   - name: fuel-swiftproxy-02
     role: swift-proxy
     internal_address: 10.0.0.112
     public_address: 10.0.1.112

  cobbler_common:
    # for Centos
    profile: "centos64_x86_64"
    # for Ubuntu
    # profile: "ubuntu_1204_x86_64"
    netboot-enabled: "1"
    # for Ubuntu
    # ksmeta: "puppet_version=2.7.19-1puppetlabs2 \
    # for Centos
    name-servers: "10.0.0.100"
    name-servers-search: "localdomain"
    gateway: 10.0.0.100
    ksmeta: "puppet_version=2.7.19-1.el6 \
      puppet_auto_setup=1 \
      puppet_master=fuel-pm.localdomain \
      puppet_enable=0 \
      ntp_enable=1 \
      mco_auto_setup=1 \
      mco_pskey=un0aez2ei9eiGaequaey4loocohjuch4Ievu3shaeweeg5Uthi \
      mco_stomphost=10.0.0.100 \
      mco_stompport=61613 \
      mco_stompuser=mcollective \
      mco_stomppassword=AeN5mi5thahz2Aiveexo \
      mco_enable=1"


fuel-controller-01:
  hostname: "fuel-controller-01"
  role: controller
  interfaces:
    eth0:
      mac: "52:54:00:0a:39:ec"
      static: "1"
      ip-address: "10.0.0.101"
      netmask: "255.255.255.0"
      dns-name: "fuel-controller-01.localdomain"
      management: "1"
    eth1:
      mac: "52:54:00:e6:dc:c9"
      static: "0"
    eth2:
      mac: "52:54:00:ae:22:04"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-controller-02:
# If you need create 'cinder-volumes' VG at install OS -- uncomment this line and  move it above in middle of ksmeta section.
# At this line you need describe list of block devices, that must come in this group.
# cinder_bd_for_vg=/dev/sdb,/dev/sdc \
  hostname: "fuel-controller-02"
  role: controller
  interfaces:
    eth0:
      mac: "52:54:00:e4:46:5c"
      static: "1"
      ip-address: "10.0.0.102"
      netmask: "255.255.255.0"
      dns-name: "fuel-controller-02.localdomain"
      management: "1"
    eth1:
      mac: "52:54:00:b4:a5:25"
      static: "0"
    eth2:
      mac: "52:54:00:28:f8:06"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-controller-03:
# If you need create 'cinder-volumes' VG at install OS -- uncomment this line and  move it above in middle of ksmeta section.
# At this line you need describe list of block devices, that must come in this group.
# cinder_bd_for_vg=/dev/sdb,/dev/sdc \
  hostname: "fuel-controller-03"
  role: controller
  interfaces:
    eth0:
      mac: "52:54:00:09:04:40"
      static: "1"
      ip-address: "10.0.0.103"
      netmask: "255.255.255.0"
      dns-name: "fuel-controller-03.localdomain"
      management: "1"
    eth1:
      mac: "52:54:00:78:23:b7"
      static: "0"
    eth2:
      mac: "52:54:00:84:60:bf"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-quantum:
  hostname: "fuel-quantum"
  role: quantum
  interfaces:
    eth0:
      mac: "52:54:00:68:ff:9b"
      static: "1"
      ip-address: "10.0.0.105"
      netmask: "255.255.255.0"
      dns-name: "fuel-quantum.localdomain"
      management: "1"
    eth1:
      mac: "52:54:00:27:49:44"
      static: "0"
    eth2:
      mac: "52:54:00:19:0d:56"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-compute-01:
  hostname: "fuel-compute-01"
  role: compute
  interfaces:
    eth0:
      mac: "52:54:00:68:ff:9b"
      static: "1"
      ip-address: "10.0.0.110"
      netmask: "255.255.255.0"
      dns-name: "fuel-compute-01.localdomain"
      management: "1"
    eth1:
      mac: "52:54:00:27:49:44"
      static: "0"
    eth2:
      mac: "52:54:00:19:0d:56"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"

fuel-compute-02:
  hostname: "fuel-compute-02"
  role: compute
  interfaces:
    eth0:
      mac: "52:54:00:68:ff:9b"
      static: "1"
      ip-address: "10.0.0.111"
      netmask: "255.255.255.0"
      dns-name: "fuel-compute-02.localdomain"
      management: "1"
    eth1:
      mac: "52:54:00:27:49:44"
      static: "0"
    eth2:
      mac: "52:54:00:19:0d:56"
      static: "1"
  interfaces_extra:
    eth0:
      peerdns: "no"
    eth1:
      peerdns: "no"
    eth2:
      promisc: "yes"
      userctl: "yes"
      peerdns: "no"
