- id: controller_end
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/controller.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-compute
  type: puppet
  groups: [compute]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/compute.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-cinder
  type: puppet
  groups: [cinder]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/cinder.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-ceph-osd
  type: puppet
  groups: [ceph-osd]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/ceph-osd.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-primary-mongo
  type: puppet
  groups: [primary-mongo]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/mongo_primary.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-mongo
  type: puppet
  groups: [mongo]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/mongo.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

