- id: controller_remaining_tasks
  type: puppet
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/controller.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-compute
  type: puppet
  groups: [compute]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  cross-depends:
    - name: keystone
    - name: openstack-controller
    - name: /(primary-)?rabbitmq/
  refresh_on: [nova_config, nova_paste_api_ini]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/compute.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-cinder
  type: puppet
  groups: [cinder, cinder-block-device, cinder-vmware]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  cross-depends:
    - name: openstack-cinder
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/cinder.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-primary-mongo
  type: puppet
  groups: [primary-mongo]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/mongo.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-mongo
  type: puppet
  groups: [mongo]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/mongo.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: ironic-conductor
  type: puppet
  groups: [ironic]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  cross-depends:
    - name: ironic
    - name: /(primary-)?database/
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/roles/ironic-conductor.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
