- id: controller_remaining_tasks
  type: puppet
  version: 2.0.0
  groups: [primary-controller, controller]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/controller.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-compute
  type: puppet
  version: 2.0.0
  groups: [compute]
  required_for: [enable_nova_compute_service]
  requires: [hosts, firewall]
  cross-depends:
    - name: keystone
    - name: /(primary-)?openstack-controller/
    - name: /(primary-)?rabbitmq/
    - name: memcached
  refresh_on: [nova_config, nova_paste_api_ini]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/compute.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-cinder
  type: puppet
  version: 2.1.0
  groups: [cinder, cinder-block-device, cinder-vmware]
  required_for: [enable_cinder_volume_service]
  requires: [hosts, firewall]
  cross-depends:
    - name: openstack-cinder
  condition:
    yaql_exp: >
      changedAny($.cinder, $.get('cinder_volume_group'),
      $.network_metadata.nodes.get(concat(\"node-\", $.uid)).network_roles.get('cinder/iscsi'),
      $.network_metadata.vips, $.debug, $.node_volumes, $.storage, $.rabbit, $.ceilometer,
      $.get('use_stderr'), $.get('use_syslog'), $.get('syslog_log_facility_cinder'),
      $.get('syslog_log_facility_ceph'), $.get('proxy_port'), $.get('kombu_compression'),
      $.get('use_ssl'), $.get('service_endpoint'), $.get('glance_api_servers'))
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/cinder.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: enable_cinder_volume_service
  type: puppet
  version: 2.0.0
  groups: [cinder, cinder-block-device]
  requires: [top-role-cinder]
  required_for: [deploy_end]
  condition:
    yaql_exp: >
      changedAny($.cinder, $.get('cinder_volume_group'),
      $.network_metadata.nodes.get(concat(\"node-\", $.uid)).network_roles.get('cinder/iscsi'),
      $.network_metadata.vips, $.debug, $.node_volumes, $.storage, $.rabbit, $.ceilometer,
      $.get('use_stderr'), $.get('use_syslog'), $.get('syslog_log_facility_cinder'),
      $.get('syslog_log_facility_ceph'), $.get('proxy_port'), $.get('kombu_compression'),
      $.get('use_ssl'), $.get('service_endpoint'), $.get('glance_api_servers'))
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/enable_cinder.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /

- id: top-role-primary-mongo
  type: puppet
  version: 2.0.0
  groups: [primary-mongo]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/mongo.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: top-role-mongo
  type: puppet
  version: 2.0.0
  groups: [mongo]
  cross-depends:
    - name: top-role-primary-mongo
  required_for: [deploy_end]
  requires: [hosts, firewall]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/mongo.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: ironic-conductor
  type: puppet
  version: 2.0.0
  groups: [ironic]
  required_for: [deploy_end]
  requires: [hosts, firewall]
  cross-depends:
    - name: ironic
    - name: /(primary-)?database/
    - name: /(primary-)?rabbitmq/
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/ironic-conductor.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600

- id: enable_nova_compute_service
  type: puppet
  version: 2.0.0
  groups: [compute, compute-vmware]
  requires: [top-role-compute, top-role-compute-vmware, openstack-network-compute-nova]
  required_for: [deploy_end]
  refresh_on: [nova_config, nova_paste_api_ini]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/enable_compute.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
    cwd: /

- id: allocate_hugepages
  type: puppet
  version: 2.0.0
  role: ['/.*/']
  requires: [setup_repositories]
  required_for: [globals]
  parameters:
    puppet_manifest: /etc/puppet/modules/openstack_tasks/examples/roles/allocate_hugepages.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300
    cwd: /
